//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employeess
    {
        public int EmpID { get; set; }
        public string Name { get; set; }
        public string Dept { get; set; }
        public decimal Salary { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
