//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class employeedbEntities : DbContext
    {
        public employeedbEntities()
            : base("name=employeedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Department1> Departments1 { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<employee1> employees1 { get; set; }
        public virtual DbSet<Employeess> Employeesses { get; set; }
        public virtual DbSet<employeeView> employeeViews { get; set; }
    
        public virtual int DeleteEmployee(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteEmployee", idParameter);
        }
    
        public virtual int GetSalaryById(Nullable<int> id, ObjectParameter salary)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetSalaryById", idParameter, salary);
        }
    
        public virtual int GetSaryById(Nullable<int> id, ObjectParameter salary)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetSaryById", idParameter, salary);
        }
    
        public virtual int Greet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Greet");
        }
    
        public virtual int PrintNtimes(Nullable<int> n)
        {
            var nParameter = n.HasValue ?
                new ObjectParameter("N", n) :
                new ObjectParameter("N", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PrintNtimes", nParameter);
        }
    
        public virtual ObjectResult<sp_GetEmplBYID_Result> sp_GetEmplBYID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetEmplBYID_Result>("sp_GetEmplBYID", idParameter);
        }
    
        public virtual ObjectResult<usp_GetEmployee_Result> usp_GetEmployee(Nullable<int> empID)
        {
            var empIDParameter = empID.HasValue ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetEmployee_Result>("usp_GetEmployee", empIDParameter);
        }
    }
}
